import uuid
import random
import datetime
import threading
import json
import time
import pandas as pd
from pathlib import Path
from typing import Dict, Any, List

from .llm_provider import GroqProvider
from backend.config import settings

JOBS = {}

class SyntheticEngine:
    def __init__(self, api_key: str = None, model: str = None):
        self.llm = GroqProvider(api_key=api_key, model=model)

    def plan_dataset(self, prompt: str, rows: int) -> Dict[str, Any]:
        """Calls the LLM to generate the dataset schema."""
        schema = self.llm.generate_schema(prompt)
        schema["target_rows"] = rows
        return schema

def background_generation_task(job_id: str, schema: Dict[str, Any]):
    target_rows = schema.get("target_rows", 10)
    JOBS[job_id]["status"] = "running"
    JOBS[job_id]["valid"] = 0
    
    try:
        # Extract python code generated by LLM
        code_str = schema.get("python_code", "")
        if not code_str:
            raise ValueError("No python_code generated in schema by Dataset Architect.")

        # Execute code in isolated namespace
        namespace = {}
        exec(code_str, namespace)
        
        generate_fn = namespace.get("generate_base_data")
        if not generate_fn:
            raise ValueError("python_code did not define a generate_base_data function")
            
        raw_records = generate_fn(target_rows)
        
        # Use LLM provider to fill any semantic fields that were strictly marked as 'llm'
        llm = GroqProvider(api_key=settings.groq_api_key_1, model=settings.groq_model)
        has_llm_fields = any(c.get("generation_strategy") == "llm" for c in schema.get("columns", []))
        
        if has_llm_fields:
            # Chunking to avoid massive LLM context limits and Groq TPM limits
            CHUNK_SIZE = 10
            final_records = []
            for i in range(0, len(raw_records), CHUNK_SIZE):
                chunk = raw_records[i:i+CHUNK_SIZE]
                try:
                    filled_chunk = llm.fill_semantic_fields(schema, chunk)
                except Exception as e:
                    print(f"Error filling chunk: {e}")
                    filled_chunk = chunk
                final_records.extend(filled_chunk)
                JOBS[job_id]["valid"] = len(final_records)
        else:
            final_records = raw_records
            JOBS[job_id]["valid"] = len(final_records)

        df = pd.DataFrame(final_records)
        
        # Ensure all requested columns exist even if the script missed them
        for col in schema.get("columns", []):
            if col["name"] not in df.columns:
                df[col["name"]] = None
        
        # Cast columns to their proper types
        for col in schema.get("columns", []):
            cname = col["name"]
            ctype = col["type"]
            if cname in df.columns:
                if ctype == "uuid":
                    df[cname] = [f"{i+1:02d}" for i in range(len(df))]
                elif ctype == "integer":
                    df[cname] = pd.to_numeric(df[cname], errors='coerce').fillna(0).astype(int)
                elif ctype == "float":
                    df[cname] = pd.to_numeric(df[cname], errors='coerce').astype(float).round(2)
                elif ctype == "boolean":
                    df[cname] = df[cname].astype(str).str.lower().map({'true': True, 'false': False, '1': True, '0': False}).fillna(False)

        out_path = f"/tmp/{job_id}.parquet"
        df.to_parquet(out_path)

        # Convert all to standard python types to avoid JSON serialization errors with numpy/pandas types
        preview_records = []
        for rec in df.head(10).to_dict('records'):
            clean_rec = {}
            for k, v in rec.items():
                if pd.isna(v):
                    clean_rec[k] = None
                else:
                    clean_rec[k] = str(v) if not isinstance(v, (int, float, bool, str)) else v
            preview_records.append(clean_rec)
            
        JOBS[job_id]["records"] = preview_records
        JOBS[job_id]["valid"] = len(df)
        JOBS[job_id]["artifact_path"] = out_path
        JOBS[job_id]["status"] = "completed"
        
    except Exception as e:
        print(f"[DataDesigner] Generation error: {e}")
        JOBS[job_id]["status"] = "failed"


def start_generation_job(schema: Dict[str, Any]) -> str:
    job_id = str(uuid.uuid4())
    JOBS[job_id] = {
        "status": "queued",
        "schema": schema,
        "valid": 0,
        "rejected": 0,
        "duplicates": 0,
        "records": [],
        "artifact_path": None
    }
    
    thread = threading.Thread(target=background_generation_task, args=(job_id, schema))
    thread.daemon = True
    thread.start()
    
    return job_id

def get_job_status(job_id: str) -> Dict[str, Any]:
    if job_id not in JOBS:
        return {"error": "Job not found"}
    
    job = JOBS[job_id]
    return {
        "status": job["status"],
        "valid": job["valid"],
        "rejected": job["rejected"],
        "duplicates": job["duplicates"],
        "target": job["schema"].get("target_rows", 0),
        "preview": job["records"]
    }

def get_job_records(job_id: str) -> List[Dict[str, Any]]:
    # Instead of in-memory list, this endpoint should probably return the path or full df dict
    if job_id not in JOBS:
        return []
    path = JOBS[job_id].get("artifact_path")
    if path and Path(path).exists():
        df = pd.read_parquet(path)
        return df.to_dict('records')
    return JOBS[job_id]["records"]
