"""Problem Formulator — BIBLE §14-15.

Translates a human goal and a data understanding report into a structured
ProblemSpec that guides the rest of the orchestration.
Uses Groq/GPT OSS 120B for reasoning, with deterministic validation (Llama 3.3 70B deprecated).
"""

from __future__ import annotations

import json
from typing import Any, TypedDict

from backend.orchestrator.groq_client import chat


class ProblemSpec(TypedDict):
    needs_training: bool
    task_type: str
    modality: str
    target_column: str | None
    rationale: str


def formulate_problem(goal: str, understanding_report: dict[str, Any]) -> ProblemSpec:
    """Use GPT OSS 120B to formulate a problem spec, validated deterministically."""
    system_prompt = (
        "You are the Problem Formulator for the Unified AI Platform.\\n"
        "Your job is to read the user's GOAL and their DATA UNDERSTANDING REPORT, "
        "and output a strictly formatted JSON object with the following keys:\\n"
        "- needs_training: (boolean) false if RAG/retrieval is enough, true if a model must be trained.\\n"
        "- task_type: (string) e.g., 'classification', 'regression', 'rag', 'fine_tuning', 'object_detection'.\\n"
        "- modality: (string) 'text', 'tabular', 'image', 'multimodal'.\\n"
        "- target_column: (string or null) the column to predict if tabular, otherwise null.\\n"
        "- rationale: (string) human-readable explanation of WHY this formulation was chosen.\\n"
        "Output ONLY valid JSON, no markdown blocks."
    )
    
    user_prompt = f"GOAL: {goal}\\n\\nDATA REPORT: {json.dumps(understanding_report)}"
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    
    response = chat(messages, tools=[], max_tokens=1000)
    content = response.get("content", "{}")
    
    try:
        # Sometimes LLMs wrap in ```json ... ```
        if content and content.startswith("```json"):
            content = content.split("```json")[1].split("```")[0].strip()
        elif content and content.startswith("```"):
            content = content.split("```")[1].split("```")[0].strip()
            
        spec = json.loads(content)
    except json.JSONDecodeError:
        # Fallback if parsing completely fails
        spec = {
            "needs_training": True,
            "task_type": "unknown",
            "modality": "unknown",
            "target_column": None,
            "rationale": "Fallback due to LLM parsing error.",
        }
        
    # --- DETERMINISTIC VALIDATION / HEURISTICS ---
    # BIBLE.md §15 rules to override hallucinations
    
    goal_lower = goal.lower()
    report_str = json.dumps(understanding_report).lower()
    
    # Heuristic 1: PDFs + Q&A -> RAG
    if "pdf" in report_str and any(w in goal_lower for w in ["answer", "question", "q&a", "search"]):
        spec["needs_training"] = False
        spec["task_type"] = "rag"
        spec["modality"] = "text"
        
    # Heuristic 2: Chat logs + style -> Fine Tuning
    if ("chat" in report_str or "log" in report_str) and any(w in goal_lower for w in ["style", "tone", "personal", "respond"]):
        spec["needs_training"] = True
        spec["task_type"] = "fine_tuning"
        spec["modality"] = "text"
        
    # Heuristic 3: Tabular -> predict
    file_counts = understanding_report.get("file_type_counts", {})
    if file_counts.get("csv", 0) > 0 or file_counts.get("xlsx", 0) > 0 or file_counts.get("parquet", 0) > 0:
        spec["modality"] = "tabular"
        spec["needs_training"] = True
        if spec.get("task_type") not in ["classification", "regression", "ranking"]:
            spec["task_type"] = "classification" # safe default
            
        # Target column override if it exists in the report and the LLM missed it
        if "likely_target_column" in report_str:
            pass
            # Trust the LLM extraction of target_column if it's tabular, 
            # but we could enforce the understanding report's best guess if needed.
            
    # Ensure types
    return {
        "needs_training": bool(spec.get("needs_training", True)),
        "task_type": str(spec.get("task_type", "classification")),
        "modality": str(spec.get("modality", "tabular")),
        "target_column": spec.get("target_column"),
        "rationale": str(spec.get("rationale", "Generated by AI.")),
    }
